version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/todos
    depends_on:
      - postgres
    command: >
      sh -c "bunx prisma migrate deploy && bun run start"
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/todos
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/todos
    depends_on:
      - postgres

  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/todos
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
